const { transformTokens } = require("token-transformer");
const StyleDictionary = require("style-dictionary");
const _ = require("lodash");
const fs = require("fs");
const path = require("path");
const rimraf = require("rimraf");

// Tokens generated by Tokens Studio
const rawTokens = require("../tokens.json");

const BUILD_PATH = "dist/ios/";

// Platform options config for each style dictionary
const STYLE_DICTIONARY_BASE_PLATFORM_CONFIG = {
  transforms: [
    "attribute/cti",
    "name/cti/camel",
    "color/UIColorSwift",
    "content/swift/literal",
    "asset/swift/literal",
    "size/swift/remToCGFloat",
    "font/swift/literal",
    "custom/attribute/iosHexColor",
    "custom/name/removeColorNamespace",
  ],
  buildPath: BUILD_PATH,
};

// Template formatter for StyleGuideColors swift file
StyleDictionary.registerFormat({
  name: "custom/format/ios-ys-style-guide-colors",
  formatter: _.template(
    fs.readFileSync(
      path.join(__dirname, "..", "templates", "style-guide-colors.template")
    )
  ),
});

// Transform CSS Hex codes
StyleDictionary.registerTransform({
  type: "attribute",
  name: "custom/attribute/iosHexColor",
  matcher: (token) => token.type === "color",
  transformer: (token) => {
    token.attributes.iosHexColor = `0x${token.value
      .replace("#", "")
      .toUpperCase()}`;
  },
});

// Drop "colors" prefix from color tokens
StyleDictionary.registerTransform({
  type: "attribute",
  name: "custom/name/removeColorNamespace",
  matcher: (token) => token.type === "color",
  transformer: (token) => {
    token.name = _.camelCase(token.name.replace(/^colors/, ""));
  },
});

// token JSON formatted for Style Dictionary
const coreStyleDictionaryJSON = transformTokens(rawTokens, ["global"], [], {
  expandTypography: true,
});

const coreStyleDictionary = StyleDictionary.extend({
  tokens: coreStyleDictionaryJSON,
  platforms: {
    ios: {
      ...STYLE_DICTIONARY_BASE_PLATFORM_CONFIG,
      files: [
        {
          destination: "StyleGuideColors.swift",
          format: "custom/format/ios-ys-style-guide-colors",
        },
      ],
    },
  },
});

module.exports = {
  buildiOSTokens: async function () {
    await rimraf(BUILD_PATH);
    [coreStyleDictionary].forEach((styleDictionary) =>
      styleDictionary.buildAllPlatforms()
    );
  },
};
