const { transformTokens } = require("token-transformer");
const StyleDictionary = require("style-dictionary");
const _ = require("lodash");

// Tokens generated by Tokens Studio
const rawTokens = require("../tokens.json");

// Platform options config for each style dictionary
const STYLE_DICTIONARY_BASE_PLATFORM_CONFIG = {
  transformGroup: "css",
  transforms: [
    "attribute/cti",
    "name/cti/kebab",
    "time/seconds",
    "content/icon",
    "size/rem",
    "color/css",
    "boxShadow",
    "px",
  ],
  prefix: "ys",
  buildPath: "dist/web/",
};

// Custom transform for box shadow values
StyleDictionary.registerTransform({
  type: "value",
  name: "boxShadow",
  matcher: (token) => token.type === "boxShadow",
  transformer: (token) =>
    token.value
      .reduce((boxShadowStrings, currentValue) => {
        const { x, y, spread, blur, color, type } = currentValue;
        const maybeInset = type === "innerShadow" ? "inset" : "";
        return [
          ...boxShadowStrings,
          `${x}px ${y}px ${spread}px ${blur}px ${color} ${maybeInset}`.trim(),
        ];
      }, [])
      .join(", "),
});

// Custom transform for box shadow values
StyleDictionary.registerTransform({
  type: "value",
  name: "px",
  matcher: (token) =>
    [
      "borderRadius",
      "borderWidth",
      "dimension",
      "fontSizes",
      "spacing",
    ].includes(token.type),
  transformer: (token) => `${token.value}px`,
});

// Define global set name constant
const GLOBAL = "global";
// Get set keys for all sets besides our global set
const nonGlobalSetKeys = Object.keys(rawTokens).filter(
  (key) => key !== GLOBAL && !key.startsWith("$")
);

// Format our Tokens Setudio token sets for Style Dictionary
const styleDictionaryJSON = nonGlobalSetKeys.reduce(
  (accumulator, set) => ({
    ...accumulator,
    [set]: transformTokens(rawTokens, [GLOBAL, set], [GLOBAL], {
      expandTypography: true,
    }),
  }),
  []
);

styleDictionaryJSON[GLOBAL] = transformTokens(rawTokens, [GLOBAL], [], {
  expandTypography: true,
});

const styleDictionaries = [GLOBAL, ...nonGlobalSetKeys].map((key) =>
  StyleDictionary.extend({
    tokens: styleDictionaryJSON[key],
    platforms: {
      web: {
        ...STYLE_DICTIONARY_BASE_PLATFORM_CONFIG,
        files: [
          {
            destination: `${_.kebabCase(key)}.css`,
            format: "css/variables",
          },
        ],
      },
    },
  })
);

module.exports = {
  buildWebTokens: function () {
    styleDictionaries.forEach((styleDictionary) =>
      styleDictionary.buildAllPlatforms()
    );
  },
};
