name: Ensure conventional commits

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "tokens.json"

jobs:
  run-commitlint:
    name: Run commitlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
