name: Create release for web package
env:
  GITHUB_TOKEN: ${{ github.token }}

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Bump web package version
        run: npx semantic-release --extends ./web/release.package-bump.config.js

      - name: Open pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(web): release"
          title: "Release web"
          base: main
          labels: automated-pr
          branch: "release-web-${{ steps.get-next-version.outputs.new-release-version }}"
          delete-branch: true
