name: Build Tokens
env:
  GITHUB_TOKEN: ${{ github.token }}

on:
  push:
    branches:
      - main
    paths:
      - "tokens.js"

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Build Tokens
        run: npm run build-tokens

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Built platform tokens [skip ci]"
          git push origin HEAD:main
