name: Publish Web Package
env:
  GITHUB_TOKEN: ${{ github.token }}

on:
  push:
    branches:
      - main
    paths:
      - "dist/web/"
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Publish
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
