name: Publish web packages

on:
  push:
    paths:
      - "web/package.json"
  workflow_dispatch:

jobs:
  cloudsmith:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for Cloudsmith
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish
