name: Style Dictionary
env:
  GITHUB_TOKEN: ${{ github.token }}

on:
  push:
    branches:
      - main
    paths:
      - "tokens.json"
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Transform to Style Dictionary
        run: npm run style-dictionary

      - name: Extract PR number
        id: pr_number
        run: echo "pr_number=$(gh pr view $GITHUB_SHA --json number -q .number || echo "")" >> "$GITHUB_OUTPUT"

      - name: Open pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: transform tokens${{ steps.pr_number.outputs.pr_number && ' from ${{ steps.pr_number.outputs.pr_number }}' }} to Style Dictionary"
          title: "Transform tokens${{ steps.pr_number.outputs.pr_number && ' from ${{ steps.pr_number.outputs.pr_number }}' }} to Style Dictionary"
          base: main
          labels: automated-pr
          branch: tokens-studio-to-style-dictionary
          delete-branch: true
