name: Style Dictionary
env:
  GITHUB_TOKEN: ${{ github.token }}

on:
  push:
    branches:
      - main
    paths:
      - "tokens.json"
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Transform to Style Dictionary
        run: npm run style-dictionary

      - name: Extract PR number
        id: pr_number
        run: |
          merge_commits () { git log --merges --reverse --oneline --ancestry-path $1..origin | grep "Merge pull request";  }
          pr_number () { merge_commits $1 | head --lines 1 | sed --silent "s/^.*Merge pull request #\\s*\\([0-9]*\\).*$/\\1/p"; }
          echo "pr_number=$(git pr-number ${{ github.event.head_commit }})" >> "$GITHUB_OUTPUT"

      - name: Open pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: transform tokens${{ steps.pr_number.outputs.pr_number && ' from ${{ steps.pr_number.outputs.pr_number }}' }} to Style Dictionary"
          title: "Transform tokens${{ steps.pr_number.outputs.pr_number && ' from ${{ steps.pr_number.outputs.pr_number }}' }} to Style Dictionary"
          base: main
          labels: automated-pr
          branch: tokens-studio-to-style-dictionary
          delete-branch: true
