name: Style Dictionary
env:
  GITHUB_TOKEN: ${{ github.token }}

on:
  push:
    branches:
      - main
    paths:
      - "tokens.json"
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Transform to Style Dictionary
        run: npm run style-dictionary

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Open pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: transform tokens from ${{ steps.vars.outputs.sha_short }} to Style Dictionary"
          title: "Transform tokens from ${{ steps.vars.outputs.sha_short }} to Style Dictionary"
          body: "This PR transforms design tokens exported from Tokens Studio in ${{ steps.vars.outputs.sha_short }} to Style Dictionary JSON."
          base: main
          labels: automated-pr
          branch: tokens-studio-to-style-dictionary
          delete-branch: true
